name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [pull_request]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: update apt repository
        run: sudo apt-get update
      - name: install dependency
        run: sudo apt-get install build-essential g++ libyaml-dev libexplain-dev
      - name: install libfswatch
        run: wget https://github.com/emcrisostomo/fswatch/releases/download/1.17.1/fswatch-1.17.1.tar.gz && tar xzvf fswatch-1.17.1.tar.gz && cd fswatch-1.17.1 && configure && make && sudo make install
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: compile
        run: gcc main.c -o fswatch-reloader -lyaml -lfswatch -lexplain